# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict_cpp <- function(x, is_na, roots, yes, no, missing, is_leaf, feature, split, value) {
    .Call('_treeshap_predict_cpp', PACKAGE = 'treeshap', x, is_na, roots, yes, no, missing, is_leaf, feature, split, value)
}

new_covers <- function(x, is_na, roots, yes, no, missing, is_leaf, feature, split) {
    .Call('_treeshap_new_covers', PACKAGE = 'treeshap', x, is_na, roots, yes, no, missing, is_leaf, feature, split)
}

treeshap_cpp <- function(x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover) {
    .Call('_treeshap_treeshap_cpp', PACKAGE = 'treeshap', x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover)
}

treeshap_interactions_cpp <- function(x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover) {
    .Call('_treeshap_treeshap_interactions_cpp', PACKAGE = 'treeshap', x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover)
}

