# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

treeshap_cpp <- function(x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover) {
    .Call('_treeshap_treeshap_cpp', PACKAGE = 'treeshap', x_size, fulfills, roots, yes, no, missing, feature, is_leaf, value, cover)
}

