on:
  push:
    branches:
      - master
      - 'issue*'
      - 'gh-actions'
      - 'githubactions'
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: macOS-r-4.0-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys:  macOS-r-4.0-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "randomForest"))
          remotes::install_github('catboost/catboost', subdir = 'catboost/R-package')
          PKG_URL <- "https://github.com/microsoft/LightGBM/releases/download/v3.0.0/lightgbm-3.0.0-r-cran.tar.gz"
          remotes::install_url(PKG_URL)
          Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = "false")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
